config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
require_dependency 'admin_constraint'
require_dependency 'entity_constraint'

# rubocop is bad and recommends insane things
Rails.application.routes.draw do
  constraints(subdomain: 'era') do
    mount Oaisys::Engine, at: '/oai'

    root to: 'welcome#index'

    resources :items, only: [:show, :edit] do
      collection do
        post :create_draft, controller: 'items/draft', action: :create
      end

      delete :delete_draft, to: 'items/draft#destroy'

      resources :draft, only: [:show, :update], controller: 'items/draft'
      resources :files, only: [:create, :destroy], controller: 'items/files' do
        member do
          patch :set_thumbnail
        end
      end

      member do
        get 'download/:file_set_id', to: 'downloads#download', format: false, as: 'file_download'
        get 'view/:file_set_id/*file_name', to: 'downloads#view', format: false, as: 'file_view'
      end
    end

    get 'search', to: 'search#index'
    get 'profile', to: 'profile#index'

    resources :communities, only: [:index, :show] do
      resources :collections, only: [:show]
    end

    namespace :admin, constraints: AdminConstraint.new do
      root to: 'dashboard#index'

      resources :users, only: [:index, :show] do
        member do
          patch :suspend
          patch :unsuspend
          patch :grant_admin
          patch :revoke_admin
          post :login_as_user
        end
      end

      resources :communities do
        resources :collections, except: [:index]
      end

      resources :items, only: [:index, :destroy]

      resources :theses, only: [] do
        collection do
          post :create_draft, controller: 'theses/draft', action: :create
        end

        delete :delete_draft, to: 'theses/draft#destroy'

        resources :draft, only: [:show, :update], controller: 'theses/draft'
        resources :files, only: [:create, :destroy], controller: 'theses/files' do
          member do
            patch :set_thumbnail
          end
        end
      end

      resources :announcements, only: [:index, :destroy, :create]
    end

    post '/logout_as_user', to: 'sessions#logout_as_user'
    match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post], as: :login
    match '/auth/failure', to: 'sessions#failure', via: [:get, :post]
    match '/logout', to: 'sessions#destroy', via: [:get, :post]
    post '/auth/system', to: 'sessions#system_login'

    # Sidekiq panel
    if Rails.env.development?
      mount Sidekiq::Web => '/sidekiq'
    else
      mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
    end

    get 'sitemap.xml', to: 'sitemap#index', defaults: { format: :xml }, as: :sitemapindex
    get 'sitemap-communities.xml', to: 'sitemap#communities', defaults: { format: :xml }, as: :communities_sitemap
    get 'sitemap-collections.xml', to: 'sitemap#collections', defaults: { format: :xml }, as: :collections_sitemap
    get 'sitemap-items.xml', to: 'sitemap#items', defaults: { format: :xml }, as: :items_sitemap
    get 'sitemap-theses.xml', to: 'sitemap#theses', defaults: { format: :xml }

    # Dynamic robots.txt
    get 'robots.txt' => 'robots#robots'

    # Static pages
    get '/about', to: 'static_pages#about'
    get '/policies', to: 'static_pages#policies'
    get '/contact', to: 'static_pages#contact'

    ## HydraNorth URL redirects
    get '/files/:noid', to: 'redirect#hydra_north_item' # may have query string `?file=filename`
    get '/downloads/:noid', to: 'redirect#hydra_north_item' # may have query string `?file=filename`
    get '/files/:noid/:filename', to: 'redirect#hydra_north_file', constraints: { filename: /[^\/]+/ }
    get '/collections/:noid', to: 'redirect#hydra_north_community_collection'

    ## Pre-HydraNorth URL redirects
    get '/public/view/item/:uuid', to: 'redirect#fedora3_item'
    get '/public/view/item/:uuid/:ds', to: 'redirect#fedora3_datastream'
    get '/public/view/item/:uuid/:ds/:filename', to: 'redirect#fedora3_datastream', constraints: { filename: /[^\/]+/ }
    get '/public/datastream/get/:uuid/:ds', to: 'redirect#fedora3_datastream'
    get '/public/datastream/get/:uuid/:ds/:filename', to: 'redirect#fedora3_datastream',
                                                      constraints: { filename: /[^\/]+/ }
    get '/public/view/collection/:uuid', to: 'redirect#fedora3_collection'
    get '/public/view/community/:uuid', to: 'redirect#fedora3_community'

    get '/rails/blobs/:key', to: redirect('/rails/active_storage/blobs/%{key}/thumbnail.jpg')

    # AIP API v1

    namespace :aip,
              defaults: { format: :n3 } do
      namespace :v1 do
        get '/collections/:id',
            to: 'collections#show',
            as: 'collection'
        get '/:entity/:id',
            to: 'entities#show',
            as: 'entity',
            constraints: EntityConstraint.new
        get '/:entity/:id/filesets',
            to: 'entities#file_sets',
            as: 'entity_filesets',
            constraints: EntityConstraint.new
        get '/:entity/:id/file_paths',
            to: 'entities#file_paths',
            as: 'entity_file_paths',
            constraints: EntityConstraint.new
        get '/:entity/:id/filesets/:file_set_id',
            to: 'entities#file_set',
            as: 'entity_file_set',
            constraints: EntityConstraint.new
        get '/:entity/:id/filesets/:file_set_id/fixity',
            to: 'entities#fixity_file',
            as: 'entity_fileset_fixity',
            constraints: EntityConstraint.new
      end
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminController

  def index
    @items = Item.limit(10).order(record_created_at: :desc)
    @users = User.where.not(last_seen_at: nil).limit(10).order(last_seen_at: :desc)
  end

end

app/views/admin/dashboard/index.html.erb
<h1><%= t('.header') %></h1>

<div class="row my-5">
  <div class="col-md-3">
    <div class="card text-center">
    <div class="card-body">
      <h4 class="card-title"><%= t('items.index.header') %></h4>
      <div class="data">
        <%= link_to admin_items_path, class: 'btn btn-outline-primary' do %>
            <%= number_with_delimiter(Item.count + Thesis.count) %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="card text-center">
      <div class="card-body">
        <h4 class="card-title"><%= t('admin.users.index.header') %></h4>
        <%= link_to admin_users_path, class: 'btn btn-outline-primary' do %>
            <%= number_with_delimiter(User.count) %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="card text-center">
      <div class="card-body">
        <h4 class="card-title"><%= t('communities.title') %></h4>
          <%= link_to admin_communities_path, class: 'btn btn-outline-primary' do %>
            <%= number_with_delimiter(Community.count) %>
          <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="card text-center">
      <div class="card-body">
        <h4 class="card-title"><%= t('collections.title') %></h4>
        <%= link_to admin_communities_path, class: 'btn btn-outline-primary' do %>
          <%= number_with_delimiter(Collection.count) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row my-5">
  <div class="col-md-6">
    <h4><%= t('.recent_items') %></h4>
    <div class="list-group">
      <% @items.each do |item| %>
        <%= link_to item, class: 'list-group-item list-group-item-action d-flex justify-content-between align-items-start' do %>
          <%= item.title %>
          <span class="badge badge-secondary">
            <%= jupiter_time_ago_in_words(item.record_created_at) %>
          </span>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-md-6">
    <h4><%= t('.recent_users') %></h4>
    <div class="list-group">
      <% @users.each do |user| %>
        <%= link_to [:admin, user], class: 'list-group-item list-group-item-action d-flex justify-content-between align-items-start' do %>
          <%= user.name %>
          <span class="badge badge-secondary">
            <%= jupiter_time_ago_in_words(user.last_seen_at, blank_message: t('never_signed_in')) %>
          </span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="row my-5">
  <div class="col-md-3">
    <p>
      <%= t('.jupiter') %>
      <span class="badge badge-primary">
        <%= Jupiter::VERSION %>
      </span>
    </p>
  </div>
  <div class="col-md-3">
    <p>
      <%= t('.ruby') %>
      <span class="badge badge-primary">
        <%= "#{RUBY_VERSION}p#{RUBY_PATCHLEVEL}" %>
      </span>
    </p>
  </div>
  <div class="col-md-3">
    <p>
      <%= t('.rails') %>
      <span class="badge badge-primary">
        <%= Rails::VERSION::STRING.to_s %>
      </span>
    </p>
  </div>
  <div class="col-md-3">
    <p>
      <%= link_to sidekiq_web_path, target: :_blank, rel: 'noopener' do %>
        <%= t('.sidekiq') %>
        <span class="badge badge-primary">
          <%= Sidekiq::VERSION.to_s %>
        </span>
      <% end %>
    </p>
  </div>
</div>