config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
require_dependency 'admin_constraint'
require_dependency 'entity_constraint'

# rubocop is bad and recommends insane things
Rails.application.routes.draw do
  constraints(subdomain: 'era') do
    mount Oaisys::Engine, at: '/oai'

    root to: 'welcome#index'

    resources :items, only: [:show, :edit] do
      collection do
        post :create_draft, controller: 'items/draft', action: :create
      end

      delete :delete_draft, to: 'items/draft#destroy'

      resources :draft, only: [:show, :update], controller: 'items/draft'
      resources :files, only: [:create, :destroy], controller: 'items/files' do
        member do
          patch :set_thumbnail
        end
      end

      member do
        get 'download/:file_set_id', to: 'downloads#download', format: false, as: 'file_download'
        get 'view/:file_set_id/*file_name', to: 'downloads#view', format: false, as: 'file_view'
      end
    end

    get 'search', to: 'search#index'
    get 'profile', to: 'profile#index'

    resources :communities, only: [:index, :show] do
      resources :collections, only: [:show]
    end

    namespace :admin, constraints: AdminConstraint.new do
      root to: 'dashboard#index'

      resources :users, only: [:index, :show] do
        member do
          patch :suspend
          patch :unsuspend
          patch :grant_admin
          patch :revoke_admin
          post :login_as_user
        end
      end

      resources :communities do
        resources :collections, except: [:index]
      end

      resources :items, only: [:index, :destroy]

      resources :theses, only: [] do
        collection do
          post :create_draft, controller: 'theses/draft', action: :create
        end

        delete :delete_draft, to: 'theses/draft#destroy'

        resources :draft, only: [:show, :update], controller: 'theses/draft'
        resources :files, only: [:create, :destroy], controller: 'theses/files' do
          member do
            patch :set_thumbnail
          end
        end
      end

      resources :announcements, only: [:index, :destroy, :create]
    end

    post '/logout_as_user', to: 'sessions#logout_as_user'
    match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post], as: :login
    match '/auth/failure', to: 'sessions#failure', via: [:get, :post]
    match '/logout', to: 'sessions#destroy', via: [:get, :post]
    post '/auth/system', to: 'sessions#system_login'

    # Sidekiq panel
    if Rails.env.development?
      mount Sidekiq::Web => '/sidekiq'
    else
      mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
    end

    get 'sitemap.xml', to: 'sitemap#index', defaults: { format: :xml }, as: :sitemapindex
    get 'sitemap-communities.xml', to: 'sitemap#communities', defaults: { format: :xml }, as: :communities_sitemap
    get 'sitemap-collections.xml', to: 'sitemap#collections', defaults: { format: :xml }, as: :collections_sitemap
    get 'sitemap-items.xml', to: 'sitemap#items', defaults: { format: :xml }, as: :items_sitemap
    get 'sitemap-theses.xml', to: 'sitemap#theses', defaults: { format: :xml }

    # Dynamic robots.txt
    get 'robots.txt' => 'robots#robots'

    # Static pages
    get '/about', to: 'static_pages#about'
    get '/policies', to: 'static_pages#policies'
    get '/contact', to: 'static_pages#contact'

    ## HydraNorth URL redirects
    get '/files/:noid', to: 'redirect#hydra_north_item' # may have query string `?file=filename`
    get '/downloads/:noid', to: 'redirect#hydra_north_item' # may have query string `?file=filename`
    get '/files/:noid/:filename', to: 'redirect#hydra_north_file', constraints: { filename: /[^\/]+/ }
    get '/collections/:noid', to: 'redirect#hydra_north_community_collection'

    ## Pre-HydraNorth URL redirects
    get '/public/view/item/:uuid', to: 'redirect#fedora3_item'
    get '/public/view/item/:uuid/:ds', to: 'redirect#fedora3_datastream'
    get '/public/view/item/:uuid/:ds/:filename', to: 'redirect#fedora3_datastream', constraints: { filename: /[^\/]+/ }
    get '/public/datastream/get/:uuid/:ds', to: 'redirect#fedora3_datastream'
    get '/public/datastream/get/:uuid/:ds/:filename', to: 'redirect#fedora3_datastream',
                                                      constraints: { filename: /[^\/]+/ }
    get '/public/view/collection/:uuid', to: 'redirect#fedora3_collection'
    get '/public/view/community/:uuid', to: 'redirect#fedora3_community'

    get '/rails/blobs/:key', to: redirect('/rails/active_storage/blobs/%{key}/thumbnail.jpg')

    # AIP API v1

    namespace :aip,
              defaults: { format: :n3 } do
      namespace :v1 do
        get '/collections/:id',
            to: 'collections#show',
            as: 'collection'
        get '/:entity/:id',
            to: 'entities#show',
            as: 'entity',
            constraints: EntityConstraint.new
        get '/:entity/:id/filesets',
            to: 'entities#file_sets',
            as: 'entity_filesets',
            constraints: EntityConstraint.new
        get '/:entity/:id/file_paths',
            to: 'entities#file_paths',
            as: 'entity_file_paths',
            constraints: EntityConstraint.new
        get '/:entity/:id/filesets/:file_set_id',
            to: 'entities#file_set',
            as: 'entity_file_set',
            constraints: EntityConstraint.new
        get '/:entity/:id/filesets/:file_set_id/fixity',
            to: 'entities#fixity_file',
            as: 'entity_fileset_fixity',
            constraints: EntityConstraint.new
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  skip_after_action :verify_authorized

end

app/views/welcome/index.html.erb
<section class="jumbotron j-jumbotron-banner">
  <div class="container">
    <div class="col-md-6">
      <h1 class="jumbotron-heading display-4"><%= t('.welcome_header_html') %></h1>
      <h2 class="mt-3"><%= t('.welcome_lead') %></h2>
    </div>
  </div>
</section>

<div class="container">
  <div class='d-flex flex-wrap align-items-center justify-content-between my-3'>
    <h2>
      <%= t('.explore_collections') %>
    </h2>

    <%= link_to t('view_more'), communities_path, class: 'btn btn-secondary', 'aria-label' => "Check out more of ERA's communities and collections" %>
  </div>

  <%# Collection images, shown only on larger screens %>
  <div class="d-none d-md-block">
    <div class="d-flex flex-row">
      <div class="j-image-with-text mx-3 col-md-3">
        <%= link_to community_collection_path(FeaturedCollection.afns_community,
                                              FeaturedCollection.afns_journals_collection) do %>
          <%= image_pack_tag 'dept-of-agriculture.jpg', alt: '',
                                                        class: 'agriculture' %>
          <h3 class="h5"><%= t('.afns_collection') %></h3>
        <% end %>
      </div>

      <div class="d-flex flex-column align-items-end">

        <div class="d-flex flex-row mb-3">
          <div class="j-image-with-text mr-3">
            <%= link_to community_path(FeaturedCollection.research_images_community) do %>
              <%= image_pack_tag 'images-of-research.jpg', alt: '',
                                                           title: t('.images_of_research_attribution') %>
              <h3 class="h5"><%= t('.images_of_research_collection') %></h3>
            <% end %>
          </div>

          <div class="j-image-with-text">
            <%= link_to community_collection_path(FeaturedCollection.grad_studies_community,
                                                  FeaturedCollection.thesis_collection) do %>
              <%= image_pack_tag 'theses.jpg', alt: '' %>
              <h3 class="h5"><%= t('.theses_collection') %></h3>
            <% end %>
          </div>

        </div>

        <div class="j-image-with-text mt-auto">
          <%= link_to community_path(FeaturedCollection.osrin_community) do %>
            <%= image_pack_tag 'oil-sands.jpg', alt: '',
                                                title: t('.osrin_attribution') %>
            <h3 class="h5"><%= t('.osrin_collection') %></h3>
          <% end %>
        </div>

      </div>
    </div>
  </div>

  <%# List of collection links, shown only on smaller screens %>
  <div class="d-md-none list-group">
    <%= link_to t('.afns_collection'), community_collection_path(FeaturedCollection.afns_community,
                                                                 FeaturedCollection.afns_journals_collection),
                class: 'list-group-item list-group-item-action list-group-item-primary mb-3 text-dark' %>

    <%= link_to t('.images_of_research_collection'), community_path(FeaturedCollection.research_images_community),
                class: 'list-group-item list-group-item-action list-group-item-primary mb-3 text-dark' %>

    <%= link_to t('.theses_collection'), community_collection_path(FeaturedCollection.grad_studies_community,
                                                                   FeaturedCollection.thesis_collection),
                class: 'list-group-item list-group-item-action list-group-item-primary mb-3 text-dark' %>

    <%= link_to t('.osrin_collection'), community_path(FeaturedCollection.osrin_community),
                class: 'list-group-item list-group-item-action list-group-item-primary mb-3 text-dark' %>
  </div>

  <div class="row mt-5">
    <div class="col-md-6 offset-md-3">
      <%= link_to 'https://era-av.library.ualberta.ca', target: :_blank, rel: 'noopener', class: 'media bg-light p-3 border border-primary rounded text-decoration-none' do %>
        <%= icon('far', 'play-circle', class: 'fa-4x mr-3') %>
        <div class="media-body text-dark">
          <h4>
            <%= t('.era_av_header') %>
          </h4>
          <p class="mb-0">
            <%= t('.era_av_text') %>
          </p>
        </div>
      <% end %>
    </div>
  </div>

</div>