config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'
require_dependency 'admin_constraint'
require_dependency 'entity_constraint'

# rubocop is bad and recommends insane things
Rails.application.routes.draw do
  constraints(subdomain: 'era') do
    mount Oaisys::Engine, at: '/oai'

    root to: 'welcome#index'

    resources :items, only: [:show, :edit] do
      collection do
        post :create_draft, controller: 'items/draft', action: :create
      end

      delete :delete_draft, to: 'items/draft#destroy'

      resources :draft, only: [:show, :update], controller: 'items/draft'
      resources :files, only: [:create, :destroy], controller: 'items/files' do
        member do
          patch :set_thumbnail
        end
      end

      member do
        get 'download/:file_set_id', to: 'downloads#download', format: false, as: 'file_download'
        get 'view/:file_set_id/*file_name', to: 'downloads#view', format: false, as: 'file_view'
      end
    end

    get 'search', to: 'search#index'
    get 'profile', to: 'profile#index'

    resources :communities, only: [:index, :show] do
      resources :collections, only: [:show]
    end

    namespace :admin, constraints: AdminConstraint.new do
      root to: 'dashboard#index'

      resources :users, only: [:index, :show] do
        member do
          patch :suspend
          patch :unsuspend
          patch :grant_admin
          patch :revoke_admin
          post :login_as_user
        end
      end

      resources :communities do
        resources :collections, except: [:index]
      end

      resources :items, only: [:index, :destroy]

      resources :theses, only: [] do
        collection do
          post :create_draft, controller: 'theses/draft', action: :create
        end

        delete :delete_draft, to: 'theses/draft#destroy'

        resources :draft, only: [:show, :update], controller: 'theses/draft'
        resources :files, only: [:create, :destroy], controller: 'theses/files' do
          member do
            patch :set_thumbnail
          end
        end
      end

      resources :announcements, only: [:index, :destroy, :create]
    end

    post '/logout_as_user', to: 'sessions#logout_as_user'
    match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post], as: :login
    match '/auth/failure', to: 'sessions#failure', via: [:get, :post]
    match '/logout', to: 'sessions#destroy', via: [:get, :post]
    post '/auth/system', to: 'sessions#system_login'

    # Sidekiq panel
    if Rails.env.development?
      mount Sidekiq::Web => '/sidekiq'
    else
      mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
    end

    get 'sitemap.xml', to: 'sitemap#index', defaults: { format: :xml }, as: :sitemapindex
    get 'sitemap-communities.xml', to: 'sitemap#communities', defaults: { format: :xml }, as: :communities_sitemap
    get 'sitemap-collections.xml', to: 'sitemap#collections', defaults: { format: :xml }, as: :collections_sitemap
    get 'sitemap-items.xml', to: 'sitemap#items', defaults: { format: :xml }, as: :items_sitemap
    get 'sitemap-theses.xml', to: 'sitemap#theses', defaults: { format: :xml }

    # Dynamic robots.txt
    get 'robots.txt' => 'robots#robots'

    # Static pages
    get '/about', to: 'static_pages#about'
    get '/policies', to: 'static_pages#policies'
    get '/contact', to: 'static_pages#contact'

    ## HydraNorth URL redirects
    get '/files/:noid', to: 'redirect#hydra_north_item' # may have query string `?file=filename`
    get '/downloads/:noid', to: 'redirect#hydra_north_item' # may have query string `?file=filename`
    get '/files/:noid/:filename', to: 'redirect#hydra_north_file', constraints: { filename: /[^\/]+/ }
    get '/collections/:noid', to: 'redirect#hydra_north_community_collection'

    ## Pre-HydraNorth URL redirects
    get '/public/view/item/:uuid', to: 'redirect#fedora3_item'
    get '/public/view/item/:uuid/:ds', to: 'redirect#fedora3_datastream'
    get '/public/view/item/:uuid/:ds/:filename', to: 'redirect#fedora3_datastream', constraints: { filename: /[^\/]+/ }
    get '/public/datastream/get/:uuid/:ds', to: 'redirect#fedora3_datastream'
    get '/public/datastream/get/:uuid/:ds/:filename', to: 'redirect#fedora3_datastream',
                                                      constraints: { filename: /[^\/]+/ }
    get '/public/view/collection/:uuid', to: 'redirect#fedora3_collection'
    get '/public/view/community/:uuid', to: 'redirect#fedora3_community'

    get '/rails/blobs/:key', to: redirect('/rails/active_storage/blobs/%{key}/thumbnail.jpg')

    # AIP API v1

    namespace :aip,
              defaults: { format: :n3 } do
      namespace :v1 do
        get '/collections/:id',
            to: 'collections#show',
            as: 'collection'
        get '/:entity/:id',
            to: 'entities#show',
            as: 'entity',
            constraints: EntityConstraint.new
        get '/:entity/:id/filesets',
            to: 'entities#file_sets',
            as: 'entity_filesets',
            constraints: EntityConstraint.new
        get '/:entity/:id/file_paths',
            to: 'entities#file_paths',
            as: 'entity_file_paths',
            constraints: EntityConstraint.new
        get '/:entity/:id/filesets/:file_set_id',
            to: 'entities#file_set',
            as: 'entity_file_set',
            constraints: EntityConstraint.new
        get '/:entity/:id/filesets/:file_set_id/fixity',
            to: 'entities#fixity_file',
            as: 'entity_fileset_fixity',
            constraints: EntityConstraint.new
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password :api_key, validations: false
  has_many :identities, dependent: :destroy
  has_many :announcements, dependent: :destroy
  has_many :draft_items, dependent: :destroy
  has_many :draft_theses, dependent: :destroy

  has_many :items, foreign_key: :owner_id, inverse_of: :owner, dependent: :restrict_with_error
  has_many :theses, foreign_key: :owner_id, inverse_of: :owner, dependent: :restrict_with_error
  has_many :collections, foreign_key: :owner_id, inverse_of: :owner, dependent: :restrict_with_error
  has_many :communities, foreign_key: :owner_id, inverse_of: :owner, dependent: :restrict_with_error

  # We don't need to validate the format of an email address here,
  # as emails are supplied from SAML (so assuming...hopefully they are valid)
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false }

  validates :name, presence: true

  # User validation for sysatem and api key values
  #             | System | Api key | Valid |
  #             ----------------------------
  # Presence(X) |   X    |    X    | True  |
  #             |        |         | True  |
  #             |   X    |         | False |
  #             |        |    X    | False |
  #             ----------------------------

  # Check if the api key is there only if the user is a system account
  validates :api_key_digest,
            presence: { message: :present_if_system_true },
            if: -> { system && api_key_digest.blank? }

  # Check that the api key is not present if it is not a system account
  validates :api_key_digest,
            absence: { message: :blank_if_system_false },
            if: -> { !system && api_key_digest.present? }

  def update_activity!(now, remote_ip, sign_in: false)
    raise ArgumentError, :remote_ip if remote_ip.blank?
    raise ArgumentError, :now if now.blank?

    # Is the user signing in now?
    if sign_in
      self.previous_sign_in_at = last_sign_in_at
      self.previous_sign_in_ip = last_sign_in_ip
      self.last_sign_in_at = now
      self.last_sign_in_ip = remote_ip
    end
    self.last_seen_at = now
    self.last_seen_ip = remote_ip
    save!
  end

  # For masking the ID that we send to rollbar
  def id_as_hash
    Digest::SHA2.hexdigest("#{Rails.application.secrets.secret_key_base}_#{id}")
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  before_action :fetch_user, only: [:show,
                                    :suspend,
                                    :unsuspend,
                                    :grant_admin,
                                    :revoke_admin,
                                    :login_as_user]

  def index
    @search = User.ransack(params[:q])
    @search.sorts = 'last_seen_at desc' if @search.sorts.empty?

    # Postgres treats nulls first in an ordered list, lets reverse this behaviour.
    result = @search.result
    orders = result.arel.orders.map do |order|
      order.direction == :asc ? "#{order.to_sql} NULLS FIRST" : "#{order.to_sql} NULLS LAST"
    end
    result = result.except(:order).order(Arel.sql(orders.join(', '))) if orders.count > 0

    @users = result.page(params[:page])
  end

  def show
    search_query_index = UserSearchService.new(
      base_restriction_key: Item.solr_exporter_class.solr_name_for(:owner, role: :exact_match),
      value: @user.id,
      params: params,
      current_user: current_user
    )
    @results = search_query_index.results
    @search_models = search_query_index.search_models

    @draft_items = @user.draft_items.unpublished
    @draft_theses = @user.draft_theses.unpublished
  end

  def suspend
    authorize [:admin, @user]

    @user.suspended = true
    @user.save

    logger.info("Admin '#{current_user.name}' has suspended '#{@user.name}'")

    redirect_to admin_user_path(@user), notice: t('admin.users.show.suspend_flash')
  end

  def unsuspend
    authorize [:admin, @user]

    @user.suspended = false
    @user.save

    logger.info("Admin '#{current_user.name}' has unsuspended '#{@user.name}'")

    redirect_to admin_user_path(@user), notice: t('admin.users.show.unsuspend_flash')
  end

  def grant_admin
    authorize [:admin, @user]

    @user.admin = true
    @user.save

    logger.info("Admin '#{current_user.name}' has granted admin access to '#{@user.name}'")

    redirect_to admin_user_path(@user), notice: t('admin.users.show.grant_admin_flash')
  end

  def revoke_admin
    authorize [:admin, @user]

    @user.admin = false
    @user.save

    logger.info("Admin '#{current_user.name}' has revoked admin access from '#{@user.name}'")

    redirect_to admin_user_path(@user), notice: t('admin.users.show.revoke_admin_flash')
  end

  def login_as_user
    authorize [:admin, @user]

    session[:admin_id] = current_user.id

    sign_in(@user)

    logger.info("Admin '#{current_user.name}' has now logged in as'#{@user.name}'")

    # TODO: goes to users dashboard once implemented
    redirect_to root_path, notice: t('admin.users.show.login_as_user_flash', user: @user.name)
  end

  private

  def fetch_user
    @user = User.find(params[:id])
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def items_sort_link(column, sort, title = nil)
    title ||= "#{column} #{sort}"
    klass = 'dropdown-item'
    klass += ' active' if params[:sort] == column && params[:direction] == sort

    link_to title, { params: { sort: column, direction: sort } }, class: klass
  end

  # html_safe is used securely in the next two methods
  # rubocop:disable Rails/OutputSafety
  def user_role(user)
    if user.admin?
      "<span class='user-admin'>#{icon('fas', 'shield-alt')} #{t('admin.users.admin_role')}</span>".html_safe
    else
      t('admin.users.user_role')
    end
  end

  def user_status(user)
    if user.suspended?
      "<span class='user-suspended'>#{icon('fas', 'ban')} #{t('admin.users.suspended_status')}</span>".html_safe
    else
      t('admin.users.active_status')
    end
  end
  # rubocop:enable Rails/OutputSafety
end

app/views/admin/users/_users.html.erb
<table class="table table-responsive-md table-hover">
  <thead>
    <tr>
      <th><%= sort_link(@search, :email, t('admin.users.email')) %></th>
      <th><%= sort_link(@search, :name, t('admin.users.name')) %></th>
      <th><%= sort_link(@search, :created_at, t('admin.users.created')) %></th>
      <th><%= sort_link(@search, :last_seen_at, t('admin.users.last_seen_at')) %></th>
      <th><%= sort_link(@search, :admin, t('admin.users.role')) %></th>
      <th><%= sort_link(@search, :suspended, t('admin.users.status')) %></th>
    </tr>
  </thead>
  <tbody>
  <% if @users.present? %>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= link_to user.email, admin_user_path(user) %></th>
        <td><%= user.name %></td>
        <td><%= jupiter_time_tag(user.created_at) %></td>
        <td>
          <%= jupiter_time_ago_in_words(user.last_seen_at, blank_message: t('never_signed_in')) %>
        </td>
        <td><%= user_role(user) %></td>
        <td><%= user_status(user) %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td colspan="6" class="text-center">
        <%= t('.no_users_found') %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<p class="text-center">
  <%# TODO: Switch to chris' application helper results count instead %>
  <%= t('.display_users_count', shown_users_count: @users.count,
                                matching_users_count: @users.total_count,
                                total_users_count: User.count) %>
</p>
<%= paginate @users %>

app/views/admin/users/index.html.erb
<% page_title(t('.header')) %>

<h1 class="my-3"><%= t('.header') %></h1>

<%= search_form_for @search, url: admin_users_path,
                             html: { method: :get, class: 'js-autocomplete d-flex my-3 form-inline' } do |f| %>

  <div class="form-group mr-auto">
    <%= f.label :name_or_email_cont, t('search_label'), class: 'mr-sm-2' %>
    <%= f.search_field :name_or_email_cont,
                       placeholder: t('.search_placeholder'),
                       class: 'form-control' %>
  </div>

  <div class="form-group p-2">
    <%= f.label :admin_eq, t('admin.users.role'), class: 'mr-2' %>
    <%= f.select :admin_eq, options_for_select([
                                                 [t('admin.users.admin_role'), true],
                                                 [t('admin.users.user_role'), false]
                                               ], @search), { include_blank: t('all') }, { class: 'form-control' } %>
  </div>

  <div class="form-group p-2">
    <%= f.label :suspended_eq, t('admin.users.status'), class: 'mr-2' %>
    <%= f.select :suspended_eq, options_for_select([
                                                     [t('admin.users.suspended_status'), true],
                                                     [t('admin.users.active_status'), false]
                                                   ], @search), { include_blank: t('all') }, { class: 'form-control' } %>
  </div>
<% end %>

<div id="js-ajax-table">
  <%= render partial: 'users' %>
</div>

app/views/admin/users/index.js.erb
$("#js-ajax-table").hide();
$("#js-ajax-table")
  .html("<%= escape_javascript(render("users")) %>")
  .fadeIn(500);

app/views/admin/users/show.html.erb
<% page_title(@user.name) %>

<ol class="breadcrumb mb-5">
  <li class="breadcrumb-item"><%= link_to t('admin.header'), admin_root_path %></li>
  <li class="breadcrumb-item"><%= link_to t('admin.users.index.header'), admin_users_path %></li>
  <li class="breadcrumb-item active"><%= @user.email %></li>
</ol>

<div class="d-flex flex-wrap justify-content-between mb-3">
  <h1><%= @user.name %></h1>

  <div class="align-self-center">
    <% if policy([:admin, @user]).suspend? %>
      <%= link_to(suspend_admin_user_path(@user), method: :patch,
                                                  class: 'btn btn-secondary',
                                                  data: { confirm: t('.suspend_dialog', user: @user.name) }) do %>
        <%= icon('fas', 'ban') %>
        <%= t('.suspend_link_text') %>
      <% end %>
    <% end %>

    <% if policy([:admin, @user]).unsuspend? %>
      <%= link_to(unsuspend_admin_user_path(@user), method: :patch,
                                                    class: 'btn btn-secondary',
                                                    data: { confirm: t('.unsuspend_dialog', user: @user.name) }) do %>
        <%= icon('fas', 'check-circle') %>
        <%= t('.unsuspend_link_text') %>
      <% end %>
    <% end %>

    <% if policy([:admin, @user]).revoke_admin? %>
      <%= link_to(revoke_admin_admin_user_path(@user), method: :patch,
                                                       class: 'btn btn-secondary',
                                                       data: { confirm: t('.revoke_admin_dialog', user: @user.name) }) do %>
        <%= icon('fas', 'minus-circle') %>
        <%= t('.revoke_admin_link_text') %>
      <% end %>
    <% end %>

    <% if policy([:admin, @user]).grant_admin? %>
      <%= link_to(grant_admin_admin_user_path(@user), method: :patch,
                                                      class: 'btn btn-secondary',
                                                      data: { confirm: t('.grant_admin_dialog', user: @user.name) }) do %>
        <%= icon('fas', 'shield-alt') %>
        <%= t('.grant_admin_link_text') %>
      <% end %>
    <% end %>

    <% if policy([:admin, @user]).login_as_user? %>
      <%= link_to(login_as_user_admin_user_path(@user), method: :post,
                                                        class: 'btn btn-secondary',
                                                        data: { confirm: t('.login_as_user_dialog', user: @user.name) }) do %>
        <%= icon('fas', 'user-secret') %>
        <%= t('.login_as_user_link_text') %>
      <% end %>
    <% end %>
  </div>
</div>

<dl class="row">
  <dt class="col-sm-3"><%= t('admin.users.email') %></dt>
  <dd class="col-sm-9">
    <%= @user.email %>
  </dd>

  <dt class="col-sm-3"><%= t('admin.users.role') %></dt>
  <dd class="col-sm-9">
    <%= user_role(@user) %>
  </dd>

  <dt class="col-sm-3"><%= t('admin.users.status') %></dt>
  <dd class="col-sm-9">
    <%= user_status(@user) %>
  </dd>

  <dt class="col-sm-3"><%= t('admin.users.created') %></dt>
  <dd class="col-sm-9">
    <%= jupiter_time_tag(@user.created_at) %>
  </dd>

  <dt class="col-sm-3"><%= t('admin.users.last_seen_at') %></dt>
  <dd class="col-sm-9">
    <%= jupiter_time_ago_in_words(@user.last_seen_at, blank_message: t('never_signed_in')) %>
  </dd>
</dl>

<%= render partial: 'profile/user_items',
           locals: { draft_items_header: t('.draft_items_header'),
                     draft_theses_header: t('.draft_theses_header'),
                     items_header: t('.items_header') } %>